services:
  no-as-a-service:
    image: ghcr.io/claytonfuselier/no-as-a-service:latest
    container_name: no-as-a-service
#    ports:
#      - "8080:3000"
    environment:
      TZ: "UTC"
      # Optional - Environment Parameters
      #LISTEN_PORT: 3000
      #API_ENDPOINT: "/nope"
      #RATE_LIMIT_REQUESTS: 200
      #RATE_LIMIT_SECONDS: 120
      #RATE_LIMIT_OVERRIDES: '{"127.0.0.1":500}'
      #REDIRECT_ROOT_ENABLED: true
      #REDIRECT_ROOT_DEST: "https://github.com/claytonfuselier/no-as-a-service"
    restart: unless-stopped
