name: Build and Publish Docker image

on:
  push:
    branches:
      - main           # Only auto-build on push to main
    paths-ignore:      # Won't trigger workflow if only these files are edited
      - '.github/**'
      - 'assets/**'
      - 'docs/**'
      - '**/*.md'
      
  workflow_dispatch:   # Allow manual build for any branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag based on branch    # /refs/heads/main goes to 'latest', all others go to 'dev'
        id: tag
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"

          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
